version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build-and-test:
    branches:
      only:
        - master
    executor:
      name: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
      - aws-s3/sync:
          from: build
          to: 's3://personal-site-prod'
          overwrite: true
          arguments: |
                --acl public-read \
                --cache-control "max-age=86400"

workflows:
    build-and-test:
      jobs:
        - build-and-test
